# Graph edges
PLAN_EDGE = "plan"
EXECUTE_TOOLS_EDGE = "execute_tools"
EVALUATE_EDGE = "evaluate"
SYNTHESIZE_EDGE = "synthesize"
REQUEST_ANALYSIS_EDGE = "request_analysis"

# Prompt metadata
MAIN_AGENT_NAME = "main_agent"

REQUEST_ANALYSIS_PROMPT_STEP = "request_analysis"
PLANNER_PROMPT_STEP = "planner"
EVALUATOR_PROMPT_STEP = "evaluator"
SYNTHESIS_PROMPT_STEP = "synthesis"

REQUEST_ANALYSIS_PROMPT_KIND = REQUEST_ANALYSIS_PROMPT_STEP
PLANNER_PROMPT_KIND = PLANNER_PROMPT_STEP
EVALUATOR_PROMPT_KIND = EVALUATOR_PROMPT_STEP
SYNTHESIS_PROMPT_KIND = SYNTHESIS_PROMPT_STEP
