# Shared node / prompt identifiers
PLANNER_KIND = "planner"
EVALUATOR_KIND = "evaluator"
SYNTHESIS_KIND = "synthesis"
SYNTHESIZE_KIND = "synthesize"
EXECUTE_TOOLS_KIND = "execute_tools"

# Graph edges
LOAD_AGENTS_EDGE = "load_agents"
ENRICH_STATE_EDGE = "enrich_state"
ENRICH_AGENT_STATE_EDGE = "enrich_agent_state"
PROFILE_LOADING_EDGE = "load_user_profile"
SYNTHESIZE_EDGE = SYNTHESIZE_KIND
PLAN_EDGE = PLANNER_KIND
EXECUTE_TOOLS_EDGE = EXECUTE_TOOLS_KIND
EVALUATE_EDGE = EVALUATOR_KIND

# Prompt kinds
PLANNER_PROMPT_KIND = PLANNER_KIND
EVALUATOR_PROMPT_KIND = EVALUATOR_KIND
SYNTHESIS_PROMPT_KIND = SYNTHESIS_KIND
