# Shared node / prompt identifiers
REQUEST_ANALYSIS_KIND = "request_analysis"
PLANNER_KIND = "planner"
EVALUATOR_KIND = "evaluator"
SYNTHESIS_KIND = "synthesis"
SYNTHESIZE_KIND = "synthesize"
EXECUTE_TOOLS_KIND = "execute_tools"

# Graph edges
PLAN_EDGE = PLANNER_KIND
EXECUTE_TOOLS_EDGE = EXECUTE_TOOLS_KIND
EVALUATE_EDGE = EVALUATOR_KIND
SYNTHESIZE_EDGE = SYNTHESIZE_KIND
REQUEST_ANALYSIS_EDGE = REQUEST_ANALYSIS_KIND

# Prompt kinds
REQUEST_ANALYSIS_PROMPT_KIND = REQUEST_ANALYSIS_KIND
PLANNER_PROMPT_KIND = PLANNER_KIND
EVALUATOR_PROMPT_KIND = EVALUATOR_KIND
SYNTHESIS_PROMPT_KIND = SYNTHESIS_KIND
