MAIN_AGENT_NAME = "main_agent"

REQUEST_ANALYSIS_PROMPT_STEP = "request_analysis"
PLANNER_PROMPT_STEP = "planner"
SYNTHESIS_PROMPT_STEP = "synthesis"

REQUEST_ANALYSIS_PROMPT_KIND = REQUEST_ANALYSIS_PROMPT_STEP
PLANNER_PROMPT_KIND = PLANNER_PROMPT_STEP
SYNTHESIS_PROMPT_KIND = SYNTHESIS_PROMPT_STEP
